In [ ]:
'''
x_in: one input vector (size 3)
x_mat_in: matrix of 7 inputs (each row size 3)
W_1, W_2, W_3: weight matrices between layers
Activation: sigmoid for first two layers, softmax for output
'''

In [1]:
#Import NumPy and Define Activation Functions

import numpy as np

# Sigmoid activation function (used in hidden layers)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Softmax function for single vector
def soft_max_vec(vec):
    return np.exp(vec) / np.sum(np.exp(vec))

# Softmax function for entire matrix (row-wise softmax)
def soft_max_mat(mat):
    return np.exp(mat) / np.sum(np.exp(mat), axis=1).reshape(-1, 1)

In [2]:
#Forward Pass for a Single Input

def forward_single_input(x, W_1, W_2, W_3):
    # Input to Layer 1
    z1 = np.dot(x, W_1)          # shape: (3,) · (3x4) => (4,)
    a1 = sigmoid(z1)             # Apply sigmoid activation

    # Input to Layer 2
    z2 = np.dot(a1, W_2)         # shape: (4,) · (4x4) => (4,)
    a2 = sigmoid(z2)             # Apply sigmoid again

    # Input to Output Layer
    z3 = np.dot(a2, W_3)         # shape: (4,) · (4x3) => (3,)
    a3 = soft_max_vec(z3)        # Apply softmax to get class probabilities

    return a3                    # Return final output (probabilities for 3 classes)

In [3]:
#Forward Pass for a Matrix of Inputs

def forward_input_matrix(X, W_1, W_2, W_3):
    # Layer 1
    Z1 = np.dot(X, W_1)          # shape: (7x3) · (3x4) => (7x4)
    A1 = sigmoid(Z1)             # Apply sigmoid element-wise

    # Layer 2
    Z2 = np.dot(A1, W_2)         # shape: (7x4) · (4x4) => (7x4)
    A2 = sigmoid(Z2)             # Apply sigmoid element-wise

    # Output Layer
    Z3 = np.dot(A2, W_3)         # shape: (7x4) · (4x3) => (7x3)
    A3 = soft_max_mat(Z3)        # Apply softmax row-wise

    return A3                    # Return final output for all 7 inputs

In [4]:
#Test Everything

# Given input vector
x_in = np.array([0.5, 0.8, 0.2])

# Matrix of 7 input vectors
x_mat_in = np.array([
    [0.5, 0.8, 0.2],
    [0.1, 0.9, 0.6],
    [0.2, 0.2, 0.3],
    [0.6, 0.1, 0.9],
    [0.5, 0.5, 0.4],
    [0.9, 0.1, 0.9],
    [0.1, 0.8, 0.7]
])

# Weight matrices
W_1 = np.array([[2, -1, 1, 4], [-1, 2, -3, 1], [3, -2, -1, 5]])
W_2 = np.array([[3, 1, -2, 1], [-2, 4, 1, -4], [-1, -3, 2, -5], [3, 1, 1, 1]])
W_3 = np.array([[-1, 3, -2], [1, -1, -3], [3, -2, 2], [1, 2, 1]])

# Test single input
print("Output for single input x_in:")
print(forward_single_input(x_in, W_1, W_2, W_3))

# Test all inputs
print("\nOutput for matrix of inputs x_mat_in:")
print(forward_input_matrix(x_mat_in, W_1, W_2, W_3))

Output for single input x_in:
[0.72780576 0.26927918 0.00291506]

Output for matrix of inputs x_mat_in:
[[0.72780576 0.26927918 0.00291506]
 [0.62054212 0.37682531 0.00263257]
 [0.69267581 0.30361576 0.00370844]
 [0.36618794 0.63016955 0.00364252]
 [0.57199769 0.4251982  0.00280411]
 [0.38373781 0.61163804 0.00462415]
 [0.52510443 0.4725011  0.00239447]]


In [ ]:
'''
Each layer applies dot product of inputs and weights
First 2 layers use sigmoid
Last layer uses softmax for classification
Vector vs matrix inputs handled by two different functions
'''